'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cart
    Public Property id As Integer
    Public Property Userid As Nullable(Of Integer)
    Public Property Productid As Nullable(Of Integer)
    Public Property Qty As Integer

    Public Overridable Property Product As Product

End Class
