'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Product
    Public Property id As Integer
    Public Property name As String
    Public Property description As String
    Public Property Price As Nullable(Of Decimal)
    Public Property Catid As Nullable(Of Integer)
    Public Property photo As String

    Public Overridable Property Cart As ICollection(Of Cart) = New HashSet(Of Cart)
    Public Overridable Property Category As Category

End Class
